definitions:
  dtos.AddToCartResponse:
    properties:
      id:
        type: integer
    type: object
  dtos.CartItem:
    properties:
      discount:
        type: integer
      discountExpiresAt:
        type: string
      id:
        format: int64
        type: integer
      imageUrl:
        type: string
      name:
        type: string
      price:
        type: integer
      quantity:
        type: integer
    type: object
  dtos.CreateCategoryResponse:
    properties:
      id:
        type: integer
    type: object
  dtos.GetCartResponse:
    properties:
      price:
        type: integer
      products:
        items:
          $ref: '#/definitions/dtos.CartItem'
        type: array
    type: object
  dtos.GetCategoriesResponse:
    properties:
      categories:
        items:
          $ref: '#/definitions/dtos.category'
        type: array
    type: object
  dtos.GetProductsResponse:
    properties:
      products:
        items:
          $ref: '#/definitions/dtos.Product'
        type: array
    type: object
  dtos.LoginResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  dtos.Product:
    properties:
      discount:
        type: integer
      discount_expires_at:
        type: string
      id:
        type: integer
      image_url:
        type: string
      name:
        type: string
      price:
        type: integer
    type: object
  dtos.ProductByIdResponse:
    properties:
      category:
        properties:
          id:
            format: int64
            type: integer
          name:
            type: string
        type: object
      description:
        type: string
      discount:
        type: integer
      discount_expires_at:
        type: string
      existing_sizes:
        items:
          type: string
        type: array
      id:
        type: integer
      image_url:
        type: string
      name:
        type: string
      price:
        type: integer
      quantity:
        type: integer
    type: object
  dtos.RefreshResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  dtos.RegisterResponse:
    properties:
      id:
        type: integer
    type: object
  dtos.category:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  response.ErrorResponse:
    properties:
      error:
        type: string
    type: object
info:
  contact: {}
  description: Your API description
  title: Three Api
  version: "1.0"
paths:
  /admin/categories:
    post:
      consumes:
      - application/json
      description: create new category
      parameters:
      - description: category name
        in: body
        name: name
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.CreateCategoryResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - AdminAuth: []
      summary: create new category
      tags:
      - admin
  /admin/categories/{id}:
    delete:
      consumes:
      - application/json
      description: delete category
      parameters:
      - description: category id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - AdminAuth: []
      summary: delete category
      tags:
      - admin
  /admin/products:
    post:
      consumes:
      - application/json
      description: create new product
      parameters:
      - description: product name
        in: formData
        name: name
        required: true
        type: string
      - description: product description
        in: formData
        name: description
        required: true
        type: string
      - description: product proce
        in: formData
        name: price
        required: true
        type: integer
      - description: product category id
        in: formData
        name: category_id
        required: true
        type: string
      - description: product quantity
        in: formData
        name: quantity
        required: true
        type: integer
      - description: product sizes
        in: formData
        name: existing_sizes
        required: true
        type: string
      - description: product image
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.CreateCategoryResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - AdminAuth: []
      summary: create new product
      tags:
      - admin
  /admin/products/{id}:
    delete:
      consumes:
      - application/json
      description: delete product
      parameters:
      - description: product id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - AdminAuth: []
      summary: delete product
      tags:
      - admin
    patch:
      consumes:
      - application/json
      description: update product
      parameters:
      - description: product id
        in: path
        name: id
        required: true
        type: integer
      - description: new product name
        in: formData
        name: name
        type: string
      - description: new product description
        in: formData
        name: description
        type: string
      - description: new product proce
        in: formData
        name: price
        type: integer
      - description: new product quantity
        in: formData
        name: quantity
        type: integer
      - description: new product sizes
        in: formData
        name: existing_sizes
        type: string
      - description: new product image
        in: formData
        name: image
        type: file
      - description: new product discount
        in: formData
        name: discount
        type: integer
      - description: new product discount expires at (only if discount exists)
        in: formData
        name: discount_expires_at
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - AdminAuth: []
      summary: update product
      tags:
      - admin
  /auth/login:
    post:
      consumes:
      - application/json
      description: login user
      parameters:
      - description: User email
        format: email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: User password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "424":
          description: Failed Dependency
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: login user
      tags:
      - auth
  /auth/refresh:
    put:
      consumes:
      - application/json
      description: generate new pare of tokens
      parameters:
      - description: Refresh token
        in: body
        name: refresh_token
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.RefreshResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - UserAuth: []
      summary: generate new pare of tokens
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: register user
      parameters:
      - description: User email
        format: email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: User password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: register user
      tags:
      - auth
  /carts:
    delete:
      consumes:
      - application/json
      description: delete all item from cart
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - UserAuth: []
      summary: delete all item from cart
      tags:
      - carts
    get:
      consumes:
      - application/json
      description: get users cart
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.GetCartResponse'
        "204":
          description: No Content
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - UserAuth: []
      summary: get users cart
      tags:
      - carts
  /carts/{item_id}:
    delete:
      consumes:
      - application/json
      description: delete item from cart
      parameters:
      - description: item id
        in: path
        name: item_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - UserAuth: []
      summary: delete item from cart
      tags:
      - carts
  /carts/add/{product_id}:
    post:
      consumes:
      - application/json
      description: add product to cart
      parameters:
      - description: product id
        in: path
        name: product_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.AddToCartResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - UserAuth: []
      summary: add product to cart
      tags:
      - carts
  /categories:
    get:
      consumes:
      - application/json
      description: get all categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.GetCategoriesResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: get all categories
      tags:
      - categories
  /products:
    get:
      consumes:
      - application/json
      description: get products list
      parameters:
      - description: page for pagination
        in: query
        name: page
        required: true
        type: integer
      - description: enable filtering by popularity
        in: query
        name: popularity
        type: boolean
      - description: enable filtering by price
        in: query
        name: price
        type: integer
      - description: products category id
        in: query
        name: category_id
        type: integer
      - description: search patern
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.GetProductsResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: get products list
      tags:
      - products
  /products/{id}:
    get:
      consumes:
      - application/json
      description: get product by id
      parameters:
      - description: product id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.ProductByIdResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: get product by id
      tags:
      - products
securityDefinitions:
  AdminAuth:
    type: basic
  UserAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
