definitions:
  dtos.CreateCategoryResponse:
    properties:
      id:
        type: integer
    type: object
  dtos.GetCategoriesResponse:
    properties:
      categories:
        items:
          $ref: '#/definitions/dtos.category'
        type: array
    type: object
  dtos.LoginResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  dtos.RefreshResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  dtos.RegisterResponse:
    properties:
      id:
        type: integer
    type: object
  dtos.category:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  response.ErrorResponse:
    properties:
      error:
        type: string
    type: object
info:
  contact: {}
  description: Your API description
  title: Three Api
  version: "1.0"
paths:
  /admin/category:
    post:
      consumes:
      - application/json
      description: create new category
      parameters:
      - description: category name
        in: body
        name: name
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.CreateCategoryResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - AdminAuth: []
      summary: create new category
      tags:
      - admin
  /admin/category/{id}:
    delete:
      consumes:
      - application/json
      description: delete category
      parameters:
      - description: category id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - AdminAuth: []
      summary: delete category
      tags:
      - admin
  /admin/product:
    post:
      consumes:
      - application/json
      description: create new product
      parameters:
      - description: product name
        in: formData
        name: name
        required: true
        type: string
      - description: product description
        in: formData
        name: description
        required: true
        type: string
      - description: product proce
        in: formData
        name: price
        required: true
        type: integer
      - description: product category id
        in: formData
        name: category_id
        required: true
        type: string
      - description: product quantity
        in: formData
        name: quantity
        required: true
        type: integer
      - description: product sizes
        in: formData
        name: existing_sizes
        required: true
        type: string
      - description: product image
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.CreateCategoryResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - AdminAuth: []
      summary: create new product
      tags:
      - admin
  /auth/login:
    post:
      consumes:
      - application/json
      description: login user
      parameters:
      - description: User email
        format: email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: User password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "424":
          description: Failed Dependency
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: login user
      tags:
      - auth
  /auth/refresh:
    put:
      consumes:
      - application/json
      description: generate new pare of tokens
      parameters:
      - description: Refresh token
        in: body
        name: refresh_token
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.RefreshResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - UserAuth: []
      summary: generate new pare of tokens
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: register user
      parameters:
      - description: User email
        format: email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: User password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: register user
      tags:
      - auth
  /categories:
    get:
      consumes:
      - application/json
      description: get all categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.GetCategoriesResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: get all categories
      tags:
      - categories
securityDefinitions:
  AdminAuth:
    type: basic
  UserAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
